let quotes = [
  {
    word: "Imagination is more important than knowledge",
    author: "Albert Einstein",
    likes: 0,
    dislikes: 0
  },
  {
    word: "The only true wisdom is in knowing you know nothing",
    author: "Socrates",
    likes: 0,
    dislikes: 0
  },
  {
    word: "If I have seen further it is by standing on the shoulders of giants",
    author: "Isaac Newton",
    likes: 0,
    dislikes: 0
  },
  {
    word: "The unexamined life is not worth living",
    author: "Socrates",
    likes: 0,
    dislikes: 0
  },
  {
    word: "Genius is one percent inspiration and ninety-nine percent perspiration",
    author: "Thomas Edison",
    likes: 0,
    dislikes: 0
  },
  {
    word: "The greatest successes come from having the freedom to fail",
    author: "Mark Zuckerberg",
    likes: 0,
    dislikes: 0
  },
  {
    word: "The best investment you can make is in yourself",
    author: "Jeff Bezos",
    likes: 0,
    dislikes: 0
  },

  // --- 80 additional philosopher quotes ---
  { word: "Know thyself", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "The life which is unexamined is not worth living", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "Wise men speak because they have something to say; fools because they have to say something", author: "Plato", likes: 0, dislikes: 0 },
  { word: "The measure of a man is what he does with power", author: "Plato", likes: 0, dislikes: 0 },
  { word: "Happiness depends upon ourselves", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "Knowing yourself is the beginning of all wisdom", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "It does not matter how slowly you go as long as you do not stop", author: "Confucius", likes: 0, dislikes: 0 },
  { word: "The superior man is modest in his speech, but exceeds in his actions", author: "Confucius", likes: 0, dislikes: 0 },
  { word: "A journey of a thousand miles begins with a single step", author: "Lao Tzu", likes: 0, dislikes: 0 },
  { word: "He who conquers others is strong; he who conquers himself is mighty", author: "Lao Tzu", likes: 0, dislikes: 0 },
  { word: "You have power over your mind — not outside events. Realize this, and you will find strength", author: "Marcus Aurelius", likes: 0, dislikes: 0 },
  { word: "The happiness of your life depends upon the quality of your thoughts", author: "Marcus Aurelius", likes: 0, dislikes: 0 },
  { word: "It's not what happens to you, but how you react to it that matters", author: "Epictetus", likes: 0, dislikes: 0 },
  { word: "Wealth consists not in having great possessions, but in having few wants", author: "Epictetus", likes: 0, dislikes: 0 },
  { word: "Luck is what happens when preparation meets opportunity", author: "Seneca", likes: 0, dislikes: 0 },
  { word: "Begin at once to live, and count each separate day as a separate life", author: "Seneca", likes: 0, dislikes: 0 },
  { word: "Happiness is the highest good", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "Man is condemned to be free", author: "Jean-Paul Sartre", likes: 0, dislikes: 0 },
  { word: "Freedom is what you do with what's been done to you", author: "Jean-Paul Sartre", likes: 0, dislikes: 0 },
  { word: "In the depth of winter I finally learned that within me there lay an invincible summer", author: "Albert Camus", likes: 0, dislikes: 0 },
  { word: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion", author: "Albert Camus", likes: 0, dislikes: 0 },
  { word: "To be is to be perceived", author: "George Berkeley", likes: 0, dislikes: 0 },
  { word: "I think, therefore I am", author: "René Descartes", likes: 0, dislikes: 0 },
  { word: "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things", author: "René Descartes", likes: 0, dislikes: 0 },
  { word: "The life of man (in a state of nature) is solitary, poor, nasty, brutish, and short", author: "Thomas Hobbes", likes: 0, dislikes: 0 },
  { word: "The mind is furnished with ideas by experience", author: "John Locke", likes: 0, dislikes: 0 },
  { word: "Reason is, and ought only to be the slave of the passions", author: "David Hume", likes: 0, dislikes: 0 },
  { word: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe", author: "Often attributed to Albert Einstein", likes: 0, dislikes: 0 },
  { word: "Dare to know! Have the courage to use your own reason", author: "Immanuel Kant", likes: 0, dislikes: 0 },
  { word: "Act only according to that maxim whereby you can at the same time will that it should become a universal law", author: "Immanuel Kant", likes: 0, dislikes: 0 },
  { word: "God is dead. God remains dead. And we have killed him", author: "Friedrich Nietzsche", likes: 0, dislikes: 0 },
  { word: "He who has a why to live can bear almost any how", author: "Friedrich Nietzsche", likes: 0, dislikes: 0 },
  { word: "Life must be understood backward. But it must be lived forward", author: "Søren Kierkegaard", likes: 0, dislikes: 0 },
  { word: "Subjectivity is truth", author: "Søren Kierkegaard", likes: 0, dislikes: 0 },
  { word: "The world is my idea", author: "Arthur Schopenhauer", likes: 0, dislikes: 0 },
  { word: "Compassion is the basis of morality", author: "Arthur Schopenhauer", likes: 0, dislikes: 0 },
  { word: "The price of greatness is responsibility", author: "Winston Churchill", likes: 0, dislikes: 0 },
  { word: "The unexamined life is not worth living", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "Everything flows and nothing remains", author: "Heraclitus", likes: 0, dislikes: 0 },
  { word: "Character is destiny", author: "Heraclitus", likes: 0, dislikes: 0 },
  { word: "The only real wisdom is knowing you know nothing", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "It is not that we have a short time to live, but that we waste much of it", author: "Seneca", likes: 0, dislikes: 0 },
  { word: "He who is brave is free", author: "Seneca", likes: 0, dislikes: 0 },
  { word: "A man's character is his fate", author: "Heraclitus", likes: 0, dislikes: 0 },
  { word: "No man's knowledge here can go beyond his experience", author: "John Locke", likes: 0, dislikes: 0 },
  { word: "The secret of happiness is freedom, the secret of freedom is courage", author: "Thucydides", likes: 0, dislikes: 0 },
  { word: "He who is not a good servant will not be a good master", author: "Plato", likes: 0, dislikes: 0 },
  { word: "To enjoy the things we ought and to hate the things we ought has the greatest bearing on excellence of character", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "It is the mark of an educated mind to be able to entertain a thought without accepting it", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "The beginning of wisdom is the definition of terms", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "Be kind, for everyone you meet is fighting a harder battle", author: "Plato (attributed)", likes: 0, dislikes: 0 },
  { word: "We live in the best of all possible worlds", author: "Gottfried Wilhelm Leibniz", likes: 0, dislikes: 0 },
  { word: "The aim of art is to represent not the outward appearance of things, but their inward significance", author: "Aristotle", likes: 0, dislikes: 0 },
  { word: "Life is really simple, but we insist on making it complicated", author: "Confucius", likes: 0, dislikes: 0 },
  { word: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment", author: "Ralph Waldo Emerson", likes: 0, dislikes: 0 },
  { word: "What we cannot speak about we must pass over in silence", author: "Ludwig Wittgenstein", likes: 0, dislikes: 0 },
  { word: "Whereof one cannot speak, thereof one must be silent", author: "Ludwig Wittgenstein", likes: 0, dislikes: 0 },
  { word: "The greatest happiness of the greatest number is the foundation of morals and legislation", author: "Jeremy Bentham", likes: 0, dislikes: 0 },
  { word: "Give me liberty, or give me death!", author: "Patrick Henry", likes: 0, dislikes: 0 },
  { word: "Science is what you know; philosophy is what you don't know", author: "Bertrand Russell", likes: 0, dislikes: 0 },
  { word: "The good life is one inspired by love and guided by knowledge", author: "Bertrand Russell", likes: 0, dislikes: 0 },
  { word: "Everything that irritates us about others can lead us to an understanding of ourselves", author: "Carl Jung", likes: 0, dislikes: 0 },
  { word: "The most courageous act is still to think for yourself. Aloud.", author: "Coco Chanel (often paraphrased)", likes: 0, dislikes: 0 },
  { word: "To do is to be", author: "Socrates (attributed)", likes: 0, dislikes: 0 },
  { word: "To be is to do", author: "Sartre (paraphrase)", likes: 0, dislikes: 0 },
  { word: "He who knows how to wait need never despair", author: "Ovid", likes: 0, dislikes: 0 },
  { word: "No man's knowledge here can go beyond his experience", author: "John Locke", likes: 0, dislikes: 0 },
  { word: "We are what we repeatedly do. Excellence, then, is not an act, but a habit", author: "Aristotle (often attributed)", likes: 0, dislikes: 0 },
  { word: "The unexamined life is not worth living", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "It is precisely the possibility of having a different point of view that is worth preserving", author: "Isaiah Berlin", likes: 0, dislikes: 0 },
  { word: "Liberty consists in doing what one desires", author: "John Stuart Mill", likes: 0, dislikes: 0 },
  { word: "One cannot step twice in the same river", author: "Heraclitus", likes: 0, dislikes: 0 },
  { word: "Injustice anywhere is a threat to justice everywhere", author: "Martin Luther King Jr.", likes: 0, dislikes: 0 },
  { word: "Act as if what you do makes a difference. It does.", author: "William James", likes: 0, dislikes: 0 },
  { word: "The only thing I know is that I know nothing", author: "Socrates", likes: 0, dislikes: 0 },
  { word: "Be the change that you wish to see in the world", author: "Mahatma Gandhi", likes: 0, dislikes: 0 },
  { word: "An unexamined life is not worth living", author: "Socrates", likes: 0, dislikes: 0 }
];